use autotool to generate rcpp attributes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1665,6 +1665,16 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 VERSION=`head -n 1 CHANGELOG`
 echo This is BridgewellML version $VERSION
 
+# find R home and set CC/CFLAGS
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+RSCRIPT="${R_HOME}/bin/Rscript"
+
+`"${RSCRIPT}" -e "library(Rcpp);compileAttributes('.')"`
+
 
 ac_config_files="$ac_config_files DESCRIPTION"
 
